#!/usr/bin/env sh

opt=$1
smc='--recurse-submodules'

if [[ $opt == 'status' ]]; then
    git submodule "$*"
elif [[ $opt == 'pull' ]]; then
    if ! [[ $* =~ $smc ]]; then
        git submodule foreach 'git '$*''
    fi
    git $*
elif [[ $opt == 'push' ]]; then
    command="git $*"
    if ! [[ $* =~ $smc ]]; then
        command="$command $smc=on-demand"
    fi
    $command
elif [[ $opt == 'sync' ]]; then
    git pull $smc
else
    git submodule foreach 'git '$*''
fi